### ISSUE TITLE
SimpleAtlasAllocator::allocate() seems to always return None

### ISSUE THREAD

**Issue by Imberflur** [nical/guillotiere#10]
https://github.com/nical/guillotiere/blob/354b0d581074700bf6381b00956c348f3bac5500/src/allocator.rs#L1244

**Comment by Imberflur** [comment]
I think this is the correct fix, but I'm not completely sure.
https://github.com/Imberflur/guillotiere/commit/42c298f5bcf0f95f1a004360d05e25ca3711e9ed

**Comment by nical** [comment]
Oops! Indeed. Your fix is correct, and an even simpler fix is to return `result` directly.
I'll put a fix up soon unless you'd like to be the one submitting the PR.

**Comment by Imberflur** [comment]
I'm fine not submitting a PR. I tried just returning result and I think sometimes the returned rectangle is to large? I.e. larger than what was requested and larger than what is actually allocated.

**Comment by nical** [comment]
Indeed, my bad again, sorry. I haven't had time to look into this code for a while.

**Comment by nical** [comment]
Fixed in https://crates.io/crates/guillotiere/0.4.3

**Comment by Imberflur** [comment]
Awesome! Thanks for taking the time to look into this.
